# Generated by Django 4.1.5 on 2023-02-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_post_categories_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('HTML', 'Html'), ('CSS', 'Css'), ('JAVASCRIPT', 'JavaScripts'), ('PYTHON', 'Python'), ('DJANGO', 'django')], max_length=10),
        ),
    ]
