# Generated by Django 4.1.5 on 2023-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_comment_blogapp_com_created_22385d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadmin',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='admin_img/'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user_img/'),
        ),
    ]
